kthcloud/go-deploy

main.go, models/dto/body/deployment.go, models/sys/deployment/converters.go, models/sys/deployment/deployment.go, models/sys/deployment/helpers.go, pkg/app/server.go, pkg/conf/environment.go, pkg/workers/ping/ping.go, pkg/workers/ping/workers.go, service/deployment_service/deployment_service.go
Poll all deployments and report their status code
=> ping deployments

pkg/workers/status_update/helpers.go, routers/api/v1/v1_vm/snapshot.go, service/vm_service/internal_service/cs_service.go, service/vm_service/snapshot_service.go
resolves https://github.com/kthcloud/go-deploy/issues/137
=> add support for applying snapshots and fix bugs with creating snapshots

models/sys/deployment/converters.go, models/sys/deployment/helpers.go, models/sys/deployment/models.go, service/deployment_service/k8s_service/deployment_service.go, service/vm_service/cs_service/helpers/recreate_helpers.go, service/vm_service/cs_service/helpers/repair_helpers.go, test/e2e/deployments/routes_test.go
resolves https://github.com/kthcloud/go-deploy/issues/172
=> allow change internal deployment port, fix cs pfr recreate with new port and bug fixes

models/dto/body/vm.go, models/sys/deployment/converters.go, models/sys/enviroment/models.go, models/sys/vm/converters.go, models/sys/vm/models.go, models/sys/vm/vm.go, pkg/workers/migrate/migrate.go, service/deployment_service/ci_config_service.go, service/deployment_service/deployment_service.go, service/deployment_service/gitlab_service/gitlab_service.go, service/resources/harbor_generator.go, service/resources/k8s_generator.go, test/acc/subsystems/k8s/helpers.go
resolves https://github.com/kthcloud/go-deploy/issues/96
=> implement custom domains for vm http proxy, fix bad naming, and remove migrations

models/sys/vm/converters.go, pkg/subsystems/cs/vm.go, routers/api/v1/v1_vm/vm.go
resolves https://github.com/kthcloud/go-deploy/issues/204
=> fix some vms not able to renew gpu lease, and bug fixes

models/sys/deployment/gitlab_ci_model.go, pkg/subsystems/github/github.go, pkg/subsystems/github/webhook.go, pkg/subsystems/gitlab/models/job_public.go, service/deployment_service/deployment_service.go, service/deployment_service/github_service/context.go, service/deployment_service/github_service/github_service.go, service/deployment_service/github_service/helpers.go, service/deployment_service/gitlab_service/context.go, service/deployment_service/gitlab_service/gitlab_service.go, service/resources/github_generator.go, service/resources/gitlab_generator.go, service/resources/public_generator.go
resolves https://github.com/kthcloud/go-deploy/issues/233
=> fix gitlab build errors

models/db.go, models/dto/body/deployment.go, models/dto/body/team.go, models/dto/body/user.go, models/dto/uri/team.go, models/dto/uri/user.go, models/sys/deployment/storage_manager/db.go, models/sys/event/client.go, models/sys/user/db.go, models/sys/user/dto.go, models/sys/user/team/db.go, models/sys/user/team/dto.go, models/sys/user/team/params.go, models/sys/user/team/team.go, models/sys/user/user.go, pkg/metrics/metrics.go, pkg/metrics/models/metrics.go, pkg/metrics/setup.go, pkg/workers/job_execute/jobs.go, pkg/workers/metrics/workers.go, routers/api/v1/v1_deployment/deployment.go, routers/api/v1/v1_user/team.go, routers/router.go, service/deployment_service/storage_manager_service.go, service/resources/k8s_generator.go, service/user_service/team_service.go
=> add unique user metrics, fix storage manager not created, add name to user read, and bug fixes

models/dto/query/vm.go, models/sys/base/activityResource/client.go, models/sys/base/activityResource/helpers.go, models/sys/base/resource/client.go, models/sys/base/resource/helpers.go, models/sys/deployment/client.go, models/sys/deployment/storage_manager/client.go, models/sys/event/client.go, models/sys/job/client.go, models/sys/notification/client.go, models/sys/user/team/client.go, models/sys/user/team/db.go, models/sys/user/user.go, models/sys/vm/client.go, models/sys/vm/db.go, models/utils.go, routers/api/v1/utils.go, routers/api/v1/v1_deployment/deployment.go, routers/api/v1/v1_vm/vm.go, service/auth_info.go, service/deployment_service/deployment_service.go, service/notification_service/notification_service.go, service/user_service/team_service.go, service/vm_service/vm_service.go, utils/utils.go
=> add better team integrations for deployments & vms

pkg/subsystems/k8s/deployment.go, pkg/workers/migrate/migrate.go, routers/router.go, routers/routes/deployment.go, service/deployment_service/deployment_service.go, test/e2e/vms/routes_test.go
resolves https://github.com/kthcloud/go-deploy/issues/252
=> fix deployments not restarting after harbor push, fix typos, clean up old migrations

models/dto/body/deployment.go, models/dto/body/vm.go, models/sys/base/resource/helpers.go, models/sys/deployment/db.go, models/sys/deployment/deployment.go, models/sys/deployment/models.go, models/sys/vm/db.go, models/sys/vm/models.go, models/sys/vm/vm.go, pkg/subsystems/k8s/pv.go, pkg/subsystems/k8s/pvc.go, routers/api/v1/v1_deployment/deployment.go, routers/api/v1/v1_vm/vm.go, service/deployment_service/deployment_service.go, service/deployment_service/k8s_service/k8s_service.go, service/storage_manager_service/storage_manager_service.go, service/user_service/team_service.go, service/vm_service/errors.go, service/vm_service/vm_service.go, utils/utils.go
=> add notification flow for transferring vms and deployments, fix bugs with slow k8s deletions

pkg/jobs/runner.go, pkg/subsystems/cs/vm.go, service/resources/cs_generator.go, service/vm_service/cs_service/cs_service.go
resolves https://github.com/kthcloud/go-deploy/issues/272
=> fix gpu not attaching in cs, fix jobs not using entry and exit func (some activities stuck)

models/sys/deployment/client.go, models/sys/deployment/dto.go, models/sys/storage_manager/client.go, models/sys/vm/client.go, pkg/workers/ping/workers.go
resolves https://github.com/kthcloud/go-deploy/issues/274
=> add option to disable ping path

models/config/models.go, models/dto/body/deployment.go, models/sys/deployment/db.go, models/sys/deployment/dto.go, models/sys/deployment/models.go, models/sys/deployment/subsystems/helpers.go, models/sys/deployment/subsystems/models.go, pkg/subsystems/k8s/deployment.go, pkg/subsystems/k8s/hpa.go, pkg/subsystems/k8s/manifests.go, pkg/subsystems/k8s/models/deployment_public.go, pkg/subsystems/k8s/models/hpa_public.go, pkg/workers/confirm/helpers.go, routers/api/v1/v1_deployment/deployment.go, service/deployment_service/deployment_service.go, service/deployment_service/k8s_service/k8s_service.go, service/resources/k8s_generator.go
resolves https://github.com/kthcloud/go-deploy/issues/219
=> add support for controlling replica count, fix minor bugs with checking deployment quota

models/dto/body/deployment.go, service/deployment_service/k8s_service/k8s_service.go, service/resources/k8s_generator.go, service/utils.go
resolves https://github.com/kthcloud/go-deploy/issues/273
=> allow shutdown of deployment, add support for messages in placeholder image

models/sys/base/resource/helpers.go, models/sys/deployment/client.go, models/sys/deployment/db.go, models/sys/deployment/deployment.go, models/sys/deployment/models.go, models/sys/job/db.go, models/sys/team/db.go, models/sys/vm/db.go, models/utils.go, pkg/app/flag.go, pkg/intializer/test.go, pkg/subsystems/k8s/logs.go, pkg/workers/logger/logger.go, pkg/workers/logger/workers.go, routers/api/v1/v1_deployment/logs.go, service/deployment_service/gitlab_service/gitlab_service.go, service/deployment_service/k8s_service/k8s_service.go, service/deployment_service/logs_service.go
resolves https://github.com/kthcloud/go-deploy/issues/292
=> rework logging for deployments,dynamic persistence

service/deployment_service/client/client.go, service/vm_service/client/client.go, service/vm_service/vm_service.go
resolves https://github.com/kthcloud/go-deploy/issues/332
=> fix ssh bug that caused same conn string for all vms in list

README.md, models/sys/team/dto.go, service/deployment_service/ci_config_service.go
resolves https://github.com/kthcloud/go-deploy/issues/315
resolves https://github.com/kthcloud/go-deploy/issues/335
resolves https://github.com/kthcloud/go-deploy/issues/344
resolves https://github.com/kthcloud/go-deploy/issues/345
=> upgrade github actions file, fix missing parts in read me, fix bug with team members dates

routers/api/v1/v1_deployment/deployment.go, service/vm_service/cs_service/cs_service.go
resolves https://github.com/kthcloud/go-deploy/issues/361
=> delete erroneous snapshots in repair job, fix bug with 404 when updating shared deployments

models/sys/base/activityResource/helpers.go, models/sys/deployment/client.go, pkg/jobs/helpers.go, pkg/jobs/jobs.go, pkg/subsystems/k8s/logs.go, pkg/workers/logger/workers.go, service/deployment_service/k8s_service/k8s_service.go, service/errors/errors.go
This PR might solve https://github.com/kthcloud/landing-frontend/issues/146
=> fix bug with log stream not starting, fix better error handling in delete resource jobs

routers/router.go
resolves https://github.com/kthcloud/go-deploy/issues/385
=> add /healthz enpoint

models/config/models.go, models/sys/sm/dto.go, models/sys/sm/sm.go, pkg/app/server.go, pkg/subsystems/k8s/k8s.go, pkg/subsystems/k8s/keys/keys.go, pkg/subsystems/k8s/logs.go, pkg/subsystems/k8s/manifests.go, pkg/subsystems/k8s/models/common.go, pkg/subsystems/k8s/models/deployment_public.go, pkg/subsystems/k8s/models/network_policy_public.go, pkg/subsystems/k8s/namespace.go, pkg/workers/migrate/migrate.go, service/constants/constants.go, service/resources/k8s_generator.go, service/v1/deployments/deployment_service.go, service/v1/deployments/k8s_service/client.go, service/v1/deployments/k8s_service/k8s_service.go, service/v1/sms/client/client.go, service/v1/sms/k8s_service/client.go, service/v1/sms/k8s_service/k8s_service.go, service/v1/vms/k8s_service/client.go, test/acc/subsystems/k8s/helpers.go, test/acc/subsystems/k8s/network_policy_test.go
resolves https://github.com/kthcloud/go-deploy/issues/228
=> fix user level isolation with network policies, remove per-user namespace after network policies are supported

routers/api/v1/deployment_hook.go
Hey there hope your doing good
I'm new in contributing on open source projects so maybe I'm wrong but This PR closes https://github.com/kthcloud/go-deploy/issues/480 issue.
=> fix: change Harbor to Registry in in user logs

.github/workflows/npm-package.yml, export/.gitignore, export/index.ts, export/package.json, export/tsconfig.json
package.json is added, published to https://www.npmjs.com/package/kthcloud-types
Workflow/action is not working
=> Add npm package 

dto/v1/body/zone.go, dto/v2/body/gpu_lease.go, models/config/config.go, models/model/vm_convert_v2.go, models/model/zone.go, pkg/config/config.go, routers/api/v1/deployment.go, routers/api/v1/vm.go, routers/api/v1/zone.go, routers/api/v2/gpu_lease.go, routers/api/v2/snapshot.go, routers/api/v2/vm.go, service/v1/api/api.go, service/v1/deployments/deployment_service.go, service/v1/deployments/logs_service.go, service/v1/teams/team_service.go, service/v1/vms/vm_service.go, service/v1/zones/opts/opts.go, service/v1/zones/zone_service.go, service/v2/vms/vm_service.go
Resolves https://github.com/kthcloud/go-deploy/issues/476
Resolves https://github.com/kthcloud/go-deploy/issues/478
Resolves https://github.com/kthcloud/go-deploy/issues/490
Resolves https://github.com/kthcloud/go-deploy/issues/489
Resolves https://github.com/kthcloud/go-deploy/issues/488
Resolves https://github.com/kthcloud/go-deploy/issues/486
Resolves https://github.com/kthcloud/go-deploy/issues/483
Resolves https://github.com/kthcloud/go-deploy/issues/482
=> Fix many minor bugs including API doc typos, exported ts types, keep-alive packets in log stream

pkg/db/resources/worker_status_repo/db.go, pkg/workers/common.go, pkg/workers/workers.go
Resolves https://github.com/kthcloud/go-deploy/issues/499
=> Delete workers that have not reported in 24 hours

.github/workflows/npm-package.yml, .github/workflows/test.yml, export/package.json, service/v1/vms/vm_service.go, service/v2/vms/resources/k8s_generator.go, service/v2/vms/vm_service.go
- Fix GitHub action files, new names and paths
- Bugfix http proxy targeted wrong service
=> Dev Update 1.0.0 Hotfixes

config.local.yml, pkg/config/config.go, pkg/intializer/system_services.go, scripts/local/config.yml.tmpl
- Flow control for logs to suppress K8s warning
- Add minor config validation checks
- Clean up config files fields that are no longer used
=> Maintenance update

README.md, scripts/local/README.md, scripts/local/setup.sh
- Updates to a new and fresh README!
Resolves https://github.com/kthcloud/go-deploy/issues/626
=> Update README for entire repository and local environment

models/model/vm_convert.go, models/model/vm_subsystems.go, pkg/db/migrate/migrate.go, pkg/services/cleaner/stale_resource_cleaner.go, pkg/services/confirm/common.go, pkg/services/logger/pod_logger_control.go, service/generators/k8s_generator.go, service/v2/vms/k8s_service/k8s_service.go, service/v2/vms/k8s_service/snapshot_service.go, service/v2/vms/resources/k8s_generator.go, service/v2/vms/vm_service.go, test/e2e/v2/resource_migrations/route_test.go
Resolves https://github.com/kthcloud/go-deploy/issues/655
=> Fix bug that caused VMs to be deleted and/or not accessible on rename

dto/v2/body/system_capacities.go, pkg/services/system_state_poll/capacities_worker.go, pkg/services/workers.go, routers/api/v2/user.go, service/v2/resource_migrations/resource_migration_service.go
- Fix missing API docs for user by ID discover
- Fix broken capacities fetches
- Fix typo in service workers err handling
=> Bugfixes after previous update

models/model/host.go, routers/api/v2/hosts.go, service/v2/api/api_client.go, service/v2/system/host_service.go
Added a missing parameter for the verbose host DTO to see when a host last was seen.
=> include lastSeenAt in verboseHost DTO
